dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:snaipewastaken/ppa'
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
      - libyaml-dev
      - protobuf-compiler
      - protobuf-c-compiler
      - criterion-dev
      - criterion
      - cmake
      - liblua5.3-0
      - liblua5.3-dev
      - lua5.3

branches:
  only:
  - master
  - dev

language: c

compiler: gcc

install:
  - wget https://github.com/raysan5/raylib/releases/download/3.0.0/raylib-3.0.0-Linux-amd64.tar.gz
  - sudo tar xvzf raylib-3.0.0-Linux-amd64.tar.gz --strip-components=1 -C /usr/local/

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make examples
  - ctest --extra-verbose
